# Generated by Django 6.0.3 on 2026-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=500)),
                ('payload', models.TextField()),
                ('qos', models.SmallIntegerField(default=0)),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Published')], db_index=True, default='in', max_length=3)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'MQTT Message',
                'verbose_name_plural': 'MQTT Messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MQTTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_topics', models.TextField(default='#', help_text='One MQTT topic per line. Use # to subscribe to all topics.')),
                ('auto_delete_enabled', models.BooleanField(default=False, help_text='Automatically delete message history older than the retention period.')),
                ('auto_delete_after_days', models.PositiveIntegerField(default=7, help_text='Number of days to keep message history. Checked every hour.')),
            ],
            options={
                'verbose_name': 'MQTT Settings',
                'verbose_name_plural': 'MQTT Settings',
            },
        ),
    ]
