# Generated by Django 6.0.3 on 2026-03-27 08:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttsettings',
            name='subscribed_topics',
        ),
        migrations.CreateModel(
            name='MQTTTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='MQTT topic pattern. Use # for wildcard (all), + for single level.', max_length=500)),
                ('name', models.CharField(blank=True, help_text='Optional display name (e.g. "All Sensors").', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description.')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mqtt.mqttsettings')),
            ],
            options={
                'verbose_name': 'Subscribed Topic',
                'verbose_name_plural': 'Subscribed Topics',
                'ordering': ['topic'],
            },
        ),
    ]
